# API Keys for LLM services
OPENAI_API_KEY=s...
GEMINI_API_KEY=...

# Set to: OPENAI, GEMINI, OPENAI-CLASSES, GEMINI-CLASSES
AI_LLM=GEMINI-CLASSES

# Logging configuration: OFF, ERROR, WARN, INFO, DEBUG, TRACE
LOG_LEVEL=OFF
